# Generated by Django 3.2.8 on 2021-11-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
