# Generated by Django 3.2.8 on 2021-11-03 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_rename_zipcode_employeeinfo_zip_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeInfo',
            new_name='Employee',
        ),
    ]
